### ISSUE TITLE
The constructed network is inconsistent with the network in the paper！

### ISSUE THREAD

**Issue by TachibanaYoshino** [pradeeplam/Anime-Sketch-Coloring-with-Swish-Gated-Residual-UNet#10]
In the network structure diagram of the paper, the resolution of the feature map is divided into 6 levels, but in model.py, there are only 5 resolution levels. Actually, when the number of channels of the feature map is 512, the resolution of the feature map is the smallest, which is still obtained by downsampling, and it has no horizontal connection like the right branch.
In model.py, in the final output of the right branch, the output of the horizontal swish layer of the left branch is not acquired.  

This leads to the asymmetry of the left and right branches of the network, misaligned connections.

**Comment by alexanderkoumis** [comment]
Is this the diagram you are referencing?
![image](https://user-images.githubusercontent.com/5108856/55888183-c9f9ec00-5b63-11e9-9f92-74a4e075f2de.png)
I believe our network matches the one described in the paper, our work was also reviewed by the original authors. I'm also having a hard time understanding the issue you are mentioning, can you show in the code where something should be added? Thanks!

**Comment by alexanderkoumis** [comment]
The final level of the right branch acquires the first level of the left branch here:
https://github.com/pradeeplam/Anime-Sketch-Coloring-with-Swish-Gated-Residual-UNet/blob/08c9fc55329a77ff85343989bcc6ed053e3b4a52/src/model.py#L77
`swish1` is the output of the left branch.

**Comment by TachibanaYoshino** [comment]
![image](https://user-images.githubusercontent.com/36946777/55892323-b5ac0280-5be8-11e9-97fb-4faa6a0d7c31.png)
Yes, it is the structure diagram of sgru. Sorry, I didn't find this problem while reviewing your code. Now come up again.

**Comment by TachibanaYoshino** [comment]
Oh, I found this to be no problem. I understand it wrong. Sorry. What I have changed is actually the same as what you wrote. Referring to the diagram, it is possible to understand the level of the network more easily.

**Comment by zamlz** [comment]
No worries, thanks for looking into our code. If you have any more questions feel free to make another issue ;)
