### ISSUE TITLE
about detail of train

### ISSUE THREAD

**Issue by kiraracreams** [pradeeplam/Anime-Sketch-Coloring-with-Swish-Gated-Residual-UNet#13]
i want to train model use own dataset.i trained about 4 epoch on 380000 pictures but get a bad result.i want to know how many epoch have you trained ?

**Comment by alexanderkoumis** [comment]
The results start getting good aroud 10 epochs. But you have many more pictures than us so that may be a non-issue. Can you post some examples of the bad results?
