### ISSUE TITLE
[HELP] InvalidArgumentError : ConcatOp : Dimensions of inputs should match

### ISSUE THREAD

**Issue by chinahamu** [pradeeplam/Anime-Sketch-Coloring-with-Swish-Gated-Residual-UNet#18]
code:
https://colab.research.google.com/drive/1_ITjS2r-OJzbNlPAlMKf9L7XevMWuV3Q?usp=sharing

Is the cause of this error a mismatch in the number of images in the image_bw and image_rgb folder contents?

datasets
https://drive.google.com/drive/folders/1GmEwRcu9zK3hQnqk7bTPyU273g7X4vyy?usp=sharing

**Comment by sdracula** [comment]
hello
i'm doing some similar works  ,  i wonder how did you fix this problom
