### ISSUE TITLE
Upload pretrained model and dataset

### ISSUE THREAD

**Issue by alexanderkoumis** [pradeeplam/Anime-Sketch-Coloring-with-Swish-Gated-Residual-UNet#9]
We need to upload our pretrained checkpoints and dataset used to the release section.

**Comment by alexanderkoumis** [comment]
Completed

**Comment by Tianhuo007** [comment]
It is nice work, I like it very much.  Could you tell me you your computer Hardware? 
Evaluation only work when sketch image size is below 10kb, My GPU:RTX2060

**Comment by zamlz** [comment]
@Tianhuo007 what we noticed is that the images that work best in evaluation when they are of similar size to the training data (256x256). You should be able to load larger images during evaluation without problem, but results are inconsistent. My machine uses a GTX 1080 Ti and a Ryzen 5. The pretrained model was not trained on my machine, but I could train and evaluate it.
